name: 🚀 Feature Request
description: 새로운 기능을 제안하고 싶으신가요?
title: "[기능]: "
labels: ["기능"]
body:
  - type: markdown
    attributes:
      value: |
        PyKis 커뮤니티 라이브러리의 기능 요청을 작성해 주셔서 감사합니다!

  - type: checkboxes
    attributes:
      label: 빠른 문제 해결을 위해 다음을 확인했나요?
      description: >
        PyKis [Docs](https://github.com/Soju06/python-kis/wiki)나 [Issues](https://github.com/Soju06/python-kis/issues)에서 유사한 기능이 존재하는지 확인해주세요.
      options:
        - label: >
            PyKis [Issues](https://github.com/Soju06/python-kis/issues)에서 검색했지만 유사한 기능을 찾지 못했습니다.
          required: true
  
  - type: textarea
    attributes:
      label: 기능 설명
      description: 기능에 대한 자세한 설명을 제공해 주세요. 구현에 필요한 [한국투자증권 API](https://apiportal.koreainvestment.com/apiservice/oauth2)나 예상되는 동작 방식을 설명해주세요.
      placeholder: |
        💡 기능의 목적과 설명을 제공해주세요.
    validations:
      required: true

  - type: textarea
    attributes:
      label: 사용 사례
      description: |
        기능 요청의 사용 사례를 설명해주세요. 이 기능을 어떻게 사용할 수 있을지, Python 코드 예제를 포함해주세요.
      placeholder: |
        💡 기능을 사용하는 예제 코드와 설명을 제공해주세요.
        
        ```python
        from pykis import PyKis

        kis = PyKis("secret.json", keep_token=True)

        ...
        ```

  - type: textarea
    attributes:
      label: 추가 정보
      description: 또 이야기하고 싶은 것이 있나요?

  - type: checkboxes
    attributes:
      label: PR를 통해 라이브러리에 기여하고 싶으신가요?
      description: >
        구현 방법을 잘 이해하고 있는 경우, [Pull Request](https://github.com/Soju06/python-kis/pulls) PyKis 커뮤니티 라이브러리를 개선해주세요!
      options:
        - label: 네, PR을 제출하여 도움을 주고 싶습니다!
